### ISSUE TITLE
stuck sync on 99 on android 10 queenslave

### ISSUE THREAD

**Issue by brunorolak** [hentaiOS/platform_manifest#9]
all times the sync stuck on 99% file 748/749 :/ 
Fetching projects:  99% (748/749) platform_frameworks_base
![Captura de tela de 2020-11-08 09-02-48](https://user-images.githubusercontent.com/73756906/98464379-43731980-21a1-11eb-8aec-d0234eb0cc34.png)
any solution?

**Comment by karthik558** [comment]
> all times the sync stuck on 99% file 748/749 :/
> Fetching projects: 99% (748/749) platform_frameworks_base
> ![Captura de tela de 2020-11-08 09-02-48](https://user-images.githubusercontent.com/73756906/98464379-43731980-21a1-11eb-8aec-d0234eb0cc34.png)
> any solution?

Its fine here bro , wait let me check again.

**Comment by karthik558** [comment]
> all times the sync stuck on 99% file 748/749 :/
> Fetching projects: 99% (748/749) platform_frameworks_base
> ![Captura de tela de 2020-11-08 09-02-48](https://user-images.githubusercontent.com/73756906/98464379-43731980-21a1-11eb-8aec-d0234eb0cc34.png)
> any solution?

Its fine here bro , wait let me check..

**Comment by karthik558** [comment]
> all times the sync stuck on 99% file 748/749 :/
> Fetching projects: 99% (748/749) platform_frameworks_base
> ![Captura de tela de 2020-11-08 09-02-48](https://user-images.githubusercontent.com/73756906/98464379-43731980-21a1-11eb-8aec-d0234eb0cc34.png)
> any solution?

![Screenshot_20201114-084905303](https://user-images.githubusercontent.com/53151501/99138403-4dd85c00-2656-11eb-8c4c-7add253da03c.jpg)

**Comment by brunorolak** [comment]
> > all times the sync stuck on 99% file 748/749 :/
> > Fetching projects: 99% (748/749) platform_frameworks_base
> > ![Captura de tela de 2020-11-08 09-02-48](https://user-images.githubusercontent.com/73756906/98464379-43731980-21a1-11eb-8aec-d0234eb0cc34.png)
> > any solution?
> 
> ![Screenshot_20201114-084905303](https://user-images.githubusercontent.com/53151501/99138403-4dd85c00-2656-11eb-8c4c-7add253da03c.jpg)

sure, I'll trie again here

**Comment by whyredfire** [comment]
![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
Same here, its struck at 99

**Comment by karthik558** [comment]
> ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> Same here, its struck at 99

something strange , cuz it clonned without any issues for me....

**Comment by brunorolak** [comment]
> > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > Same here, its struck at 99
> 
> something strange , cuz it clonned without any issues for me....

Did you sync queenslave branch? Here stucked again, I tried two more times, and space on disk inst a problem

**Comment by whyredfire** [comment]
> > > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > > Same here, its struck at 99
> > 
> > 
> > something strange , cuz it clonned without any issues for me....
> 
> Did you sync queenslave branch? Here stucked again, I tried two more times, and space on disk inst a problem

Exactly, I have a 1tb hard drive that even isn't half way full. Also yes, I tried queenslave branch...

**Comment by whyredfire** [comment]
> > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > Same here, its struck at 99
> 
> something strange , cuz it clonned without any issues for me....

I hope we are talking about queenslave branch...

**Comment by brunorolak** [comment]
> > > > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > > > Same here, its struck at 99
> > > 
> > > 
> > > something strange , cuz it clonned without any issues for me....
> > 
> > 
> > Did you sync queenslave branch? Here stucked again, I tried two more times, and space on disk inst a problem
> 
> Exactly, I have a 1tb hard drive that even isn't half way full. Also yes, I tried queenslave branch...

Guy I talk with Karthik, I have space too, and Android 10 isnt sync for me :(

**Comment by karthik558** [comment]
> > > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > > Same here, its struck at 99
> > 
> > 
> > something strange , cuz it clonned without any issues for me....
> 
> Did you sync queenslave branch? Here stucked again, I tried two more times, and space on disk inst a problem

No i am talking about rika (R)

**Comment by karthik558** [comment]
> > > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > > Same here, its struck at 99
> > 
> > 
> > something strange , cuz it clonned without any issues for me....
> 
> I hope we are talking about queenslave branch...

No , i am talking about rika , will try Queenslave tommarow

**Comment by whyredfire** [comment]
> No , i am talking about rika , will try Queenslave tommarow

Sad, we were talking about Queenslave since the beginning, I had no problems with rika.

**Comment by brunorolak** [comment]
> > > > ![image](https://user-images.githubusercontent.com/72072109/99368944-cf8fea00-28e1-11eb-9af4-6f828dab21fa.png)
> > > > Same here, its struck at 99
> > > 
> > > 
> > > something strange , cuz it clonned without any issues for me....
> > 
> > 
> > I hope we are talking about queenslave branch...
> 
> No , i am talking about rika , will try Queenslave tommarow

We talking about queenslave (Android 10), Rikka has sync well.. I need queenslave

**Comment by Sarisan** [comment]
Dudes, change tracking vendor/qcom/opensource/audio to LOS sources
https://github.com/hentaiOS/platform_manifest/blob/6bc0ae79e4966a6845c7257bc39aa2fc073fe11f/snippets/hentai.xml#L170

**Comment by brunorolak** [comment]
> Dudes, change tracking vendor/qcom/opensource/audio to LOS sources
> https://github.com/hentaiOS/platform_manifest/blob/6bc0ae79e4966a6845c7257bc39aa2fc073fe11f/snippets/hentai.xml#L170

How I make it?

**Comment by Sarisan** [comment]
> > Dudes, change tracking vendor/qcom/opensource/audio to LOS sources
> > https://github.com/hentaiOS/platform_manifest/blob/6bc0ae79e4966a6845c7257bc39aa2fc073fe11f/snippets/hentai.xml#L170
> 
> How I make it?

`<project path="vendor/qcom/opensource/audio" name="android_vendor_qcom_opensource_audio" groups="vendor" remote="github/LineageOS" />`

**Comment by brunorolak** [comment]
> > > Dudes, change tracking vendor/qcom/opensource/audio to LOS sources
> > > https://github.com/hentaiOS/platform_manifest/blob/6bc0ae79e4966a6845c7257bc39aa2fc073fe11f/snippets/hentai.xml#L170
> > 
> > 
> > How I make it?
> 
> `<project path="vendor/qcom/opensource/audio" name="android_vendor_qcom_opensource_audio" groups="vendor" remote="github/LineageOS" />`

okay I put, but I dont have acess to qcom of LoS source

**Comment by brunorolak** [comment]
> > > Dudes, change tracking vendor/qcom/opensource/audio to LOS sources
> > > https://github.com/hentaiOS/platform_manifest/blob/6bc0ae79e4966a6845c7257bc39aa2fc073fe11f/snippets/hentai.xml#L170
> > 
> > 
> > How I make it?
> 
> `<project path="vendor/qcom/opensource/audio" name="android_vendor_qcom_opensource_audio" groups="vendor" remote="github/LineageOS" />`

OMG WORKED!!!
